---
title: "Small analysis for Tiwari V. et al."
subtitle: <center> scRNASeq analysis </center>
author: "Eric Bautista Farrerons"
date: '`r paste("First created on November 2024. Updated on ", format(Sys.Date(), "%d %B %Y"))`'
output:
  html_document:
    css: style.css
    code_folding: hide
    fig_caption: yes
    toc: yes
    toc_float:
      collapsed: true
      smooth_scroll: true
    toc_depth: 4
    number_sections: true
---

```{r read, message=FALSE, warning=FALSE}
# Load packages and paths
library(here)
source(here::here("scripts", "install.R"))
source(here::here("scripts", "paths.R"))

# Read data
tpm.rsem <- read.table(here::here("data", "GSE118389_tpm_rsem.txt"), sep = "\t")
counts.rsem <- read.table(here::here("data", "GSE118389_counts_rsem.txt"), sep = "\t")
norm.data <- read.table(here::here("data", "GSE118389_norm_data.txt"), sep = "\t")

# Create path for results
scrnaseq_results_path <- file.path(results_path,
                          "./scrnaseq")
if (!dir.exists(scrnaseq_results_path)) {
  dir.create(scrnaseq_results_path, recursive = TRUE)
}
```

By reading the paper ([Ellisen LW et al.](https://pmc.ncbi.nlm.nih.gov/articles/PMC6123496/)
) I found that the data was already pre-processed and quality checked in `GSE118389_norm_data.txt`. There are 1189 cells left from an initial amount of 1534.

```{r barplot, message=FALSE, warning=FALSE}
# Bar plot of cell types

```
